### ISSUE TITLE
Import structure unfriendly to dora

### ISSUE THREAD

**Issue by jkrasting** [raphaeldussin/OM4-Analysis-Labs#2]
This packaging / import structure is unfriendly to Dora.  It requires setup.py to be run every time and the package to be installed if updates are made to the package.  The main issue is that the account where the web service runs has limited permissions capabilities to do this and our strategy with @adcroft to create a "menu of commits" won't be compatible with this.

https://github.com/raphaeldussin/OM4-Analysis-Labs/blob/510bd30da1eca66f5209b6ee607dfe1a04d83184/OM4_Analysis_Labs/annual_bias_1x1deg.py#L4-L5

**Comment by raphaeldussin** [comment]
This is easy to fix. I'm pushing a patch for now but having all codes sitting in a common directory is not the best solution (https://docs.python-guide.org/writing/structure/)
